-- SP-AUTH-7 / T-13.8.4 회사↔이메일 도메인 화이트리스트 시드 (DG-5, 2026-07-23 확정)
--
-- 재직 인증(자동)의 근거 테이블. 입력 회사 이메일의 도메인이 해당 회사에 등록돼 있으면
-- 도메인 인증 경로로 코드를 발송한다. 미등록 회사는 수동 승인(ops.py) 폴백.
--
-- 조사 방식: 근거 기반 워크플로우(공식 IR·개인정보처리방침·회사 공지 등 1차 출처)로 24개
-- 대기업 도메인을 확증하고, 개인 이메일 등 PII는 폐기·미보존(도메인만 사용).
--
-- ⚠️ 그룹 공용 도메인 결정(사용자 2026-07-23): 삼성 계열은 모두 @samsung.com, SK 계열은
--    모두 @sk.com 을 공유한다. 이는 **그룹 단위 재직 인증**을 의미한다 — 예: @samsung.com
--    보유자는 어느 삼성 계열사로든 인증할 수 있다(계열사 세밀 구분 없음). 편집 이력이 공개라
--    추적 가능하다는 전제의 트레이드오프. uq_company_domain 이 (COMP_ID, 도메인) 복합이라
--    한 도메인을 다수 계열사에 매핑한다. (COMP_EMAIL_HASH_VAL UNIQUE 로 한 이메일=한 계정은 유지)
--
-- 멱등: INSERT IGNORE + (COMP_ID, EMAIL_DOMAIN_NM) 복합 UNIQUE 로 재적용 안전. 미등록 slug 는 no-op.

-- ── 회사 전용 도메인 (계열 혼선 없음) ─────────────────────────────────────────
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'kt.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'kt';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'lge.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'lg_elec';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'lgchem.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'lg_chem';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'lgensol.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'lg_energy';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'lguplus.co.kr', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'lg_uplus';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'navercorp.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'naver';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'hyundai.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'hyundai_motor';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'mobis.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'hyundai_mobis';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'kia.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'kia';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'koreanair.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'korean_air';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'hanmi.co.kr', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'hanmi_pharm';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'kakaocorp.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'kakao';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'kakaobank.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'kakao_bank';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'kakaogames.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'kakao_games';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'krafton.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'krafton';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'ncsoft.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'ncsoft';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'pearlabyss.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'pearl_abyss';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'wemade.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'wemade';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'hybecorp.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'hybe';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'celltrion.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'celltrion';
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'amorepacific.com', TRUE FROM TCOMPANY WHERE COMP_ENG_NM = 'amorepacific';

-- ── 삼성 그룹 공용 도메인 samsung.com → 전 계열사(그룹단위 인증) ─────────────────
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'samsung.com', TRUE FROM TCOMPANY
   WHERE COMP_ENG_NM IN ('samsung_elec','samsung_sdi','samsung_ct','samsung_bio',
                         'samsung_life','samsung_electro','samsung_card');

-- ── SK 그룹 공용 도메인 sk.com → 전 계열사(그룹단위 인증) ─────────────────────────
INSERT IGNORE INTO TCOMPANY_EMAIL_DOMAIN (COMP_ID, EMAIL_DOMAIN_NM, ACTIVE_YN)
  SELECT COMP_ID, 'sk.com', TRUE FROM TCOMPANY
   WHERE COMP_ENG_NM IN ('sk_hynix','skt','sk_innovation');
