"""db/seed/legacy200/seed200.py — 별칭 승계 소스 동봉본 (자동 생성 — 손으로 고치지 마라).

생성: export_from_db.py, 2026-08-26, 서빙 DB(TCOMPANY+TCOMPANY_ALIAS) 도출.
원 소스(job_change 200-seed 4파일)는 은퇴 — 파이프라인 소비 필드(name·aliases)만 보존한다.
별칭 추가·수정은 이 파일이 아니라 override(company_meta.py) 또는 DB 갱신 후 재도출로 한다."""

SEED200 = [
    {'name': 'CJ CGV', 'aliases': ['CGV', 'CJCGV', '씨지브이']},
    {'name': 'CJ ENM 엔터테인먼트부문', 'aliases': ['CJ ENM', 'CJ ENM 엔터', 'CJENM', 'CJ이엔엠', 'ENM', '씨제이이엔엠', '엔터테인먼트부문']},
    {'name': 'CJ ENM 커머스부문', 'aliases': ['CJ ENM', 'CJ ONSTYLE', 'CJENM', 'CJ오쇼핑', 'CJ온스타일', '오쇼핑', '온스타일', '커머스부문']},
    {'name': 'CJ대한통운', 'aliases': ['CJ Logistics', '대한통운']},
    {'name': 'CJ올리브네트웍스', 'aliases': ['CJ OliveNetworks', 'cj_olive_networks', '올리브네트웍스']},
    {'name': 'CJ올리브영', 'aliases': ['Olive Young', '올리브영', '올영']},
    {'name': 'CJ제일제당', 'aliases': ['CJ CheilJedang', '제일제당']},
    {'name': 'CJ프레시웨이', 'aliases': ['CJ Freshway', '프레시웨이']},
    {'name': 'DB손해보험', 'aliases': ['DB손보', '동부화재']},
    {'name': 'HMM', 'aliases': ['에이치엠엠', '현대상선']},
    {'name': 'HPSP', 'aliases': ['에이치피에스피']},
    {'name': 'KT', 'aliases': ['케이티', '한국통신']},
    {'name': 'LG', 'aliases': ['LG그룹', '엘지']},
    {'name': 'LG디스플레이', 'aliases': ['LG Display', 'LGD']},
    {'name': 'LG에너지솔루션', 'aliases': ['LGES', '엘지에너지']},
    {'name': 'LG유플러스', 'aliases': ['LG U+', '엘지유플러스']},
    {'name': 'LG전자', 'aliases': ['LG Electronics', '엘지전자']},
    {'name': 'LG화학', 'aliases': ['LG Chem', '엘지화학']},
    {'name': 'LIG디펜스앤에어로스페이스(구 LIG넥스원)', 'aliases': ['LIG', 'LIG D&A', 'LIG DnA', 'LIG Nex1', 'LIG넥스원', 'LIG디펜스', 'LIG디펜스앤에어로스페이스']},
    {'name': 'LS', 'aliases': ['엘에스']},
    {'name': 'NAVER', 'aliases': ['NHN', '네이버']},
    {'name': 'NH투자증권', 'aliases': ['NH투자']},
    {'name': 'S-Oil', 'aliases': ['에스오일', '에쓰오일']},
    {'name': 'SK이노베이션', 'aliases': ['SKI', 'SK이노']},
    {'name': 'SK텔레콤', 'aliases': ['SKT', '에스케이텔레콤']},
    {'name': 'SK하이닉스', 'aliases': ['skhynix', '하이닉스']},
    {'name': '기아', 'aliases': ['KIA', '기아차']},
    {'name': '기업은행', 'aliases': []},
    {'name': '네오위즈', 'aliases': ['Neowiz']},
    {'name': '네패스', 'aliases': ['Nepes']},
    {'name': '대한항공', 'aliases': ['Korean Air']},
    {'name': '더블유게임즈', 'aliases': ['DoubleUGames']},
    {'name': '덕산네오룩스', 'aliases': ['Duksan Neolux']},
    {'name': '두산', 'aliases': ['Doosan']},
    {'name': '두산에너빌리티', 'aliases': ['Doosan Enerbility', '두산에너']},
    {'name': '레인보우로보틱스', 'aliases': ['Rainbow Robotics']},
    {'name': '롯데케미칼', 'aliases': ['Lotte Chemical']},
    {'name': '리노공업', 'aliases': ['LEENO']},
    {'name': '리메드', 'aliases': ['Remed']},
    {'name': '보로노이', 'aliases': ['Voronoi']},
    {'name': '비에이치', 'aliases': ['BH']},
    {'name': '삼성SDI', 'aliases': ['Samsung SDI']},
    {'name': '삼성물산', 'aliases': ['Samsung C&T']},
    {'name': '삼성바이오로직스', 'aliases': ['Samsung Biologics', '삼바', '삼성바이오']},
    {'name': '삼성생명', 'aliases': ['Samsung Life']},
    {'name': '삼성전기', 'aliases': ['Samsung Electro-Mechanics']},
    {'name': '삼성전자', 'aliases': ['Samsung', '삼성']},
    {'name': '삼성카드', 'aliases': ['Samsung Card']},
    {'name': '삼천당제약', 'aliases': ['삼천당']},
    {'name': '셀트리온', 'aliases': ['Celltrion']},
    {'name': '솔브레인', 'aliases': ['Soulbrain']},
    {'name': '실리콘투', 'aliases': ['Silicon2']},
    {'name': '아모레퍼시픽', 'aliases': ['Amorepacific', '아모레']},
    {'name': '아이센스', 'aliases': ['i-SENS']},
    {'name': '아이패밀리에스씨', 'aliases': ['iFamily SC', '롬앤']},
    {'name': '알테오젠', 'aliases': ['Alteogen']},
    {'name': '에이피알', 'aliases': ['APR', '메디큐브']},
    {'name': '에코프로', 'aliases': ['EcoPro']},
    {'name': '에코프로비엠', 'aliases': ['EcoPro BM', '에코프로BM']},
    {'name': '엔씨소프트(NC)', 'aliases': ['NC', 'NCSOFT', '리니지', '엔씨', '엔씨소프트']},
    {'name': '엔켐', 'aliases': ['Enchem']},
    {'name': '엠씨넥스', 'aliases': ['MCNEX']},
    {'name': '오스코텍', 'aliases': ['Oscotec']},
    {'name': '올릭스', 'aliases': ['OliX']},
    {'name': '위메이드', 'aliases': ['Wemade']},
    {'name': '유진테크', 'aliases': ['Eugene Technology']},
    {'name': '유한양행', 'aliases': ['Yuhan']},
    {'name': '이오테크닉스', 'aliases': ['EO Technics']},
    {'name': '제이엘케이', 'aliases': ['JLK']},
    {'name': '주성엔지니어링', 'aliases': ['Jusung Engineering']},
    {'name': '지놈앤컴퍼니', 'aliases': ['Genome & Company']},
    {'name': '카카오', 'aliases': ['Kakao', '다음카카오']},
    {'name': '카카오게임즈', 'aliases': ['Kakao Games']},
    {'name': '카카오뱅크', 'aliases': ['KakaoBank']},
    {'name': '카카오페이', 'aliases': ['KakaoPay']},
    {'name': '컴투스', 'aliases': ['Com2uS']},
    {'name': '케어젠', 'aliases': ['CareGen']},
    {'name': '코웨이', 'aliases': ['Coway']},
    {'name': '크래프톤', 'aliases': ['KRAFTON', '배틀그라운드']},
    {'name': '클래시스', 'aliases': ['Classys']},
    {'name': '테크윙', 'aliases': ['Techwing']},
    {'name': '텔레칩스', 'aliases': ['Telechips']},
    {'name': '티씨케이', 'aliases': ['TCK']},
    {'name': '파마리서치', 'aliases': ['Pharma Research']},
    {'name': '파크시스템스', 'aliases': ['Park Systems']},
    {'name': '펄어비스', 'aliases': ['Pearl Abyss', '검은사막']},
    {'name': '하이브', 'aliases': ['Big Hit', 'HYBE', '빅히트']},
    {'name': '한미반도체', 'aliases': ['Hanmi Semiconductor']},
    {'name': '한미약품', 'aliases': ['Hanmi Pharm']},
    {'name': '한화', 'aliases': ['Hanwha', '한화그룹']},
    {'name': '한화시스템', 'aliases': ['Hanwha Systems']},
    {'name': '한화에어로스페이스', 'aliases': ['Hanwha Aerospace', '한화에어로']},
    {'name': '한화오션', 'aliases': ['Hanwha Ocean', '대우조선']},
    {'name': '현대글로비스', 'aliases': ['Glovis', '글로비스']},
    {'name': '현대로템', 'aliases': ['Hyundai Rotem']},
    {'name': '현대모비스', 'aliases': ['Mobis', '모비스']},
    {'name': '현대무벡스', 'aliases': ['Hyundai Muvex']},
    {'name': '현대오토에버', 'aliases': ['Hyundai AutoEver']},
    {'name': '현대자동차', 'aliases': ['Hyundai', '현대차', '현차']},
    {'name': '현대제철', 'aliases': ['Hyundai Steel']},
    {'name': '효성중공업', 'aliases': ['Hyosung Heavy']},
    {'name': '휴젤', 'aliases': ['Hugel', '보톡스']},
]
